### ISSUE TITLE
Icons not being displayed 

### ISSUE THREAD

**Issue by timroesner** [instacart/Snacks#120]
Hi,

Pretty new to this framework so this might be trivial.

We are having an issue where the icons are only displayed as boxes, we made sure that radium is installed and also imported the components needed (Button, Icon). Using only the sample code from the docs
```jsx
<Button iconPosition="right" icon={<Icon name="arrowRightSmallBold" />} snacksStyle="secondary" size="standard">
    View 24 more
 </Button>
```

This is the result:
<img width="175" alt="screen shot 2018-02-26 at 11 35 38 am" src="https://user-images.githubusercontent.com/13894518/36691156-3a05a456-1ae9-11e8-9ad6-4b9e78d497b8.png">

**Comment by dcocchia** [comment]
Hey @timroesner, sorry for the long silence! We're not used to having people use Snacks outside of Instacart just yet so our communication is bit lacking.

Snacks is still in pre-release, so there are a few issues here and there. This one is probably the worst issue, and is currently solved by using `SetStyles`. This will give you the `ic-icons` font-set. 

This is not a great solution, which is why we're still in pre-release :D The plan is to convert the icon font to SVGs before moving to our first full release. If you're ok with the above solution for now, you can move forward for now. But be ready for breaking changes in upcoming releases.

**Comment by timroesner** [comment]
Hi @dcocchia 
Thank you for this work around, that will help us for now. 
Luckily it's just a student project, so nothing too serious if anything breaks. We're big fans of your textfields and are now prepared if other things don't work as expected.

Keep it up, we really enjoy this framework so far.

**Comment by dcocchia** [comment]
Adding @spencerschack to this one since he'll be working on the SVG converion of the icon font.

**Comment by timroesner** [comment]
Quick update on this issue:

We installed the latest build from the master branch and and noticed that on mobile the icons either become random emoji (iPhone) or will not be displayed at all (Android)

**Comment by dcocchia** [comment]
Hey @timroesner - this means the icon font is not loading correctly. The new build will still require the above work around until we finish the svg font. 

If you're using the workaround and still seeing issues, I'd check the network calls from those devices to see if the call for the font is failing. If the call is failing, the font asset is somehow being blocked or mishandled.

**Comment by dcocchia** [comment]
Fixed with https://github.com/instacart/Snacks/pull/155

Keep in mind, this is still a transition for us. We are still in pre-release :)
